#.SILENT

help:
	@echo "Author: Olaolu Akinsete"
	@echo "            "
	@echo "	Commands: "
	@echo " help - show this message"
	@echo "	install-reactjs - Install reactjs "
	@echo "	test-producer	- Run the unit tests for the procuder"
	@echo "	deps - Check for all dependecies"

install-reactjs: 
	@echo "Install reactjs for frontend"
#sudo ln -s /usr/bin/nodejs /usr/bin
	mkdir frontend_dev
	sudo create-react-app frontend_dev
