DEV_DIR = dev
DEV_FRONTEND_DIR = dev/frontend_dev

setup-reactjs-project:
	@echo "	Setting up reactjs for frontend"
	sudo bash $(DEV_FRONTEND_DIR)/utils\
	/shell-scripts/setups/reactjs-setup.sh

setup-docker-registry:
	@echo "	Setting up docker registry"
	sudo bash $
